[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-wtf>=1.2.2",
    "flask>=3.1.2",
    "pillow>=11.3.0",
    "werkzeug>=3.1.3",
    "gunicorn>=23.0.0",
]
